#! /usr/bin/bash

target="cached"
if [[ $# == 1 ]]; then
	target="$1"
	for t in $(ls $(git rev-parse --show-toplevel)/tests/*$target*.cpp); do 
		bazel test //tests:$(basename $t ".cpp") --config=unit_testing -j 6
	done
else
	bazel test //tests:$target --config=unit_testing -j 6
fi
